name: docker
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build docker image
      run: |
        docker build -t jonpulsifer/ddnsb0t:${{ github.sha }} .
    - name: Container security scan
      uses: Azure/container-scan@v0
      with:
        image-name: jonpulsifer/ddnsb0t:${{ github.sha }}
    - name: Lint Dockerfile
      uses: Shopify/gh-action-hadolint@master
